input_dir: "data_input/videos/"           # Directory for input images/videos
output_dir: "infer_output/"         # Directory to save annotated outputs
model_name: "fcos_resnet50_fpn"  # Model name for object detection
model_weights_class: "FCOS_ResNet50_FPN_Weights"
model_weights: "COCO_V1"
threshold: 0.7               # Confidence threshold for predictions
coco_labels:            # List of supported class labels
  - person,
  - bicycle,
  - car,
  - motorcycle,
  - airplane,
  - bus,
  - train,
  - truck,
  - boat,
  - traffic light,
  - fire hydrant,
  - stop sign,
  - parking meter,
  - bench,
  - bird,
  - cat,
  - dog,
  - horse,
  - sheep,
  - cow,
  - elephant,
  - bear,
  - zebra,
  - giraffe,
  - backpack,
  - umbrella,
  - handbag,
  - tie,
  - suitcase,
  - frisbee,
  - skis,
  - snowboard,
  - sports ball,
  - kite,
  - baseball bat,
  - baseball glove,
  - skateboard,
  - surfboard,
  - tennis racket,
  - bottle,
  - wine glass,
  - cup,
  - fork,
  - knife,
  - spoon,
  - bowl,
  - banana,
  - apple,
  - sandwich,
  - orange,
  - broccoli,
  - carrot,
  - hot dog,
  - pizza,
  - donut,
  - cake,
  - chair,
  - couch,
  - potted plant,
  - bed,
  - dining table,
  - toilet,
  - tv,
  - laptop,
  - mouse,
  - remote,
  - keyboard,
  - cell phone,
  - microwave,
  - oven,
  - toaster,
  - sink,
  - refrigerator,
  - book,
  - clock,
  - vase,
  - scissors,
  - teddy bear,
  - hair drier,
  - toothbrush