input_dir: "data_input/images/"           # Directory for input images/videos
output_dir: "infer_output/"         # Directory to save annotated outputs
task: "semantic_segmentation"            # image_classification|object_detection|semantic_segmentation|keypoint_detection
model_name: "fcn_resnet50"  # Model name for object detection
model_weights_class: "FCN_ResNet50_Weights"
model_weights: "DEFAULT"
threshold: 0.4               # Confidence threshold for predictions
