input_dir: "data_input/videos/"           # Directory for input images/videos
output_dir: "infer_output/"         # Directory to save annotated outputs
task: "object_detection"            # image_classification|object_detection|semantic_segmentation|keypoint_detection
model_name: "ssdlite320_mobilenet_v3_large"  # Model name for object detection
model_weights_class: "SSDLite320_MobileNet_V3_Large_Weights"
model_weights: "COCO_V1"
threshold: 0.4               # Confidence threshold for predictions
