input_dir: "data_input/videos/"           # Directory for input images/videos
output_dir: "infer_output/"         # Directory to save annotated outputs
task: "object_detection"            # image_classification|object_detection|semantic_segmentation|keypoint_detection
model_name: "ssd300_vgg16"  # Model name for object detection
model_weights_class: "SSD300_VGG16_Weights"
model_weights: "DEFAULT"
threshold: 0.4               # Confidence threshold for predictions
